language: node_js
node_js:
  - "12"
cache:
  directories:
    - ~/.npm
git:
  depth: 3

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $VALIDATION_FORM
  commit_message: "Deploy Release"
  on:
    branch: gh-pages
