language: node_js
notifications:
  email: false
node_js:
  - "12"
cache:
  directories:
    - ~/.npm
git:
  depth: 3

jobs:
  script:
    - npm install
    - npm run build
  deploy:
    provider: pages
    edge: true
    skip-cleanup: true
    keep-history: true
    github-token: $VALIDATION_FORM
    local-dir: dist/
    target-branch: gh-pages
    commit_message: "Deploy Release"
    on:
      branch: master
