language: node_js
node_js:
  - "12"
cache:
  directories:
    - ~/.npm
git:
  depth: 3
script:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $VALIDATION_FORM
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master
